<template>
    <div class="container col-1 d-block" style="margin-left: 170px;">
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
        <p>Inventário</p>
    </div>
</template>
